// Profile
export const ACTION_GET_CORPORATE_PROFILE_REQUEST = '@ACTION/GET/CORPORATE/PROFILE/REQUEST';
export const ACTION_PATCH_CORPORATE_PROFILE_REQUEST = '@ACTION/PATCH/CORPORATE/PROFILE/REQUEST';
export const ACTION_POST_PUBLISH_CORPORATE_PROFILE_REQUEST = '@ACTION/POST/PUBLISH/CORPORATE/PROFILE/REQUEST';

// CREATE JOB (HIRING CRITERIA, JOBS)
export const ACTION_GET_CORPORATE_HIRING_REQUEST = '@ACTION/GET/CORPORATE/HIRING/REQUEST';
export const ACTION_GET_CORPORATE_HIRING_RESPONSE = '@ACTION/GET/CORPORATE/HIRING/RESPONSE';
export const ACTION_POST_CORPORATE_HIRING_REQUEST = '@ACTION/GET/CORPORATE/HIRING/ADDHIRING/REQUEST';
export const ACTION_POST_PUBLISH_CORPORATE_HIRING_REQUEST = '@ACTION/POST/PUBLISH/CORPORATE/HIRING/REQUEST';
export const ACTION_GET_CORPORATE_JOBS_REQUEST = '@ACTION/GET/CORPORATE/HIRING/JOBS/REQUEST';
export const ACTION_GET_CORPORATE_JOBS_RESPONSE = '@ACTION/GET/CORPORATE/HIRING/JOBS/RESPONSE';
export const ACTION_POST_CORPORATE_JOBS_REQUEST = '@ACTION/GET/CORPORATE/HIRING/ADDJOBS/REQUEST';
export const ACTION_POST_PUBLISH_CORPORATE_JOBS_REQUEST = '@ACTION/POST/PUBLISH/CORPORATE/JOBS/REQUEST';

// Other Information
export const ACTION_POST_ADD_OTHER_INFORMATION_REQUEST = '@ACTION/POST/ADD/OTHER-INFORMATION/REQUEST';
export const ACTION_POST_PUBLISH_OTHER_INFORMATION_REQUEST = '@ACTION/POST/PUBLISH/OTHER-INFORMATION/REQUEST';

// Common
export const ACTION_GET_DEPENDENCY_LOOKUPS_REQUEST = '@ACTION/GET/DEPENDENCY/LOOKUPS/REQUEST';
export const ACTION_GET_COUNTRY_CODES_REQUEST = '@ACTION/GET/COUNTRY/CODES/REQUEST';